[package]
name = "pgrs"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
async-trait = "0.1"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tokio-postgres = "0.7"
